### ISSUE TITLE
Feature request: A method to load all sections or fields in an item

### ISSUE THREAD

**Issue by ShravanSunder** [1Password/onepassword-sdk-js#52]
### Use Case

It would be much easier to load data for a .env file if we could load all the fiends in a section/item with a single service account call.  

We could use this to populate a dict for dot env variables.  I would find this much easier to use. related: https://github.com/1Password/onepassword-sdk-python/issues/56

![2024-06-15 0633 Brave Browser Use secret references with 1Password CLI  1Password Developer](https://github.com/1Password/onepassword-sdk-python/assets/5294949/3e63e5c7-e69d-4170-8472-30db58de0b43)

### Requirements and desired behavior

Currently load single fields

**Comment by AndyTitu** [comment]
Hey @ShravanSunder, thank you for this feature request! 

From my understanding of your use case, what could already be doing is:

```
// Retrieves item
	item, err := client.Items.Get(context.Background(), existingVaultID, existingItemID)
	if err != nil {
		panic(err)
	}
	
	allSectionsOfTheItem := item.Sections
        allFieldsOfTheItem := item.Fields
```

Let me know if this solves your problem!

**Comment by ShravanSunder** [comment]
@AndyTitu wouldn't this be multiple requests?  We'd hit the rate limit very quickly with somthing like this

**Comment by SimonBarendse** [comment]
@ShravanSunder This would be a single API call for just the `client.Items.Get` request. The server response already contains all sections and fields on the item. When you `item.Sections` this doesn't trigger any additional HTTP requests.

**Comment by ShravanSunder** [comment]
oh thanks @SimonBarendse! to confirm the above is possible with py and ts libs too?

**Comment by SimonBarendse** [comment]
Yes, that's right.
