### ISSUE TITLE
Authentication Issue -@1password/sdk@0.1.0-beta.11

### ISSUE THREAD

**Issue by ryanrmcintyre** [1Password/onepassword-sdk-js#64]
### Scenario & Reproduction Steps

I have a service account token. It works fine with the op cli. I logged the token to the console to make sure it's there and is correct. Additionally I have tried using the vault id and the item id's instead of the names. Any help is appreciated!

I have the following code:
```
import { createClient } from "@1password/sdk";

async function getSecret() {
    if (!process.env.OP_SERVICE_ACCOUNT_TOKEN) {
        throw new Error("OP_SERVICE_ACCOUNT_TOKEN environment variable is not set")
    };
    // Creates an authenticated client.
    const client = await createClient({
      auth: process.env.OP_SERVICE_ACCOUNT_TOKEN,
      // Set the following to your own integration name and version.
      integrationName: "My 1Password Integration",
      integrationVersion: "v1.0.0",
    });
    // names
    const vault = 'SPTestVault';
    const item = 'TestItem';
    const field = 'username';
    // ids
    const vaultId = 'vaultIdhere';
    const itemId = `itemIdhere`;
    
    // get secret.
    const secret = await client.secrets.resolve(`op://${vault}/${item}/${field}`);
    console.log(secret);
}

getSecret();
```

### Actual Behavior

the behavior is a rejection with the an authentication error:
```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "authentication error: http error: error issuing the request".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

### Expected Behavior

I expect the secret to come back the same way `op` gives me the secret.
`op item get TestItem --vault SPTestVault --format json --fields username`
```
{
  "id": "username",
  "type": "STRING",
  "purpose": "USERNAME",
  "label": "username",
  "value": "testItemUser",
  "reference": "op://SPTestVault/TestItem/username"
}
```

### SDK version

@1password/sdk@0.1.0-beta.11

**Comment by MOmarMiraj** [comment]
Hello @ryanrmcintyre ,

Thanks for raising this issue, I will be glad to assist you.

Did you create the Service Account Token using the CLI? If so, there is currently a bug with the SDKs not correctly parsing the CLI generated service account tokens. I have flagged this to the team and look out on the release notes to see when it will be addressed.

A workaround for now is creating a Service Account through the 1Password Website if applicable for your use-case. The link below is a step by step guide on how to generate it.

https://developer.1password.com/docs/service-accounts/get-started/

If you have any more questions, don't hesitate to ask!

**Comment by ryanrmcintyre** [comment]
> Hello @ryanrmcintyre ,
> 
> Thanks for raising this issue, I will be glad to assist you.
> 
> Did you create the Service Account Token using the CLI? If so, there is currently a bug with the SDKs not correctly parsing the CLI generated service account tokens. I have flagged this to the team and look out on the release notes to see when it will be addressed.
> 
> A workaround for now is creating a Service Account through the 1Password Website if applicable for your use-case. The link below is a step by step guide on how to generate it.
> 
> https://developer.1password.com/docs/service-accounts/get-started/
> 
> If you have any more questions, don't hesitate to ask!

Thank you for your quick response! I contacted our admin and they notified me that the service account was created through the web.

**Comment by MOmarMiraj** [comment]
Thanks @ryanrmcintyre for the information.

Have you tried running the example code with your service account token? Does it still provide the same error?

Also, could you provide me with your setup information and Node.js version or any important info that can be used for diagnostic purposes.

**Comment by ryanrmcintyre** [comment]
> Thanks @ryanrmcintyre for the information.
> 
> Have you tried running the example code with your service account token? Does it still provide the same error?
> 
> Also, could you provide me with your setup information and Node.js version or any important info that can be used for diagnostic purposes.

Yes. The test code linked in the summary is using the service token:
```
op user get --me
ID:                     4AGV7L4IK5DNRNRF35RH7ZPFR4
Name:                   sa-StateProvision
Email:                  wqbosybn6zia6@1passwordserviceaccounts.com
State:                  ACTIVE
Type:                   SERVICE_ACCOUNT
Created:                1 hour ago
Updated:                1 hour ago
Last Authentication:    1 second ago
```

**Comment by ryanrmcintyre** [comment]
> Thanks @ryanrmcintyre for the information.
> 
> Have you tried running the example code with your service account token? Does it still provide the same error?
> 
> Also, could you provide me with your setup information and Node.js version or any important info that can be used for diagnostic purposes.

Yes. The test code linked in the summary is using the service token:

sdk version: `@1password/sdk@0.1.0-beta.11`
OS: `macOS Sonoma v14.5`
```
node --version
v20.14.0

op user get --me
ID:                     <id>
Name:                   sa-StateProvision
Email:                  <email>
State:                  ACTIVE
Type:                   SERVICE_ACCOUNT
Created:                1 hour ago
Updated:                1 hour ago
Last Authentication:    1 second ago
```

**Comment by ryanrmcintyre** [comment]
@MOmarMiraj I went ahead and pulled down the project and tested with `npm run commonjs-example` and `npm run esm-example` (replacing with our vault id) and both failed with the same.

**Comment by MOmarMiraj** [comment]
Hi @ryanrmcintyre 

Thanks for providing the information above, everything looks in order... Please provide me with the exact steps you took to create your service account token?

**Comment by ryanrmcintyre** [comment]
@MOmarMiraj hey there! Asked our 1Password admin and they replied:
`I logged into the 1password web console > developer tools > directory > access tokens - service account`

**Comment by ryanrmcintyre** [comment]
we can go ahead and close this issue. it was a security program blocking it 👎 thank you for your help and sorry for the inconvenience!
