### ISSUE TITLE
"Cannot find module" error due to `release/version.js`

### ISSUE THREAD

**Issue by SeriousBug** [1Password/onepassword-sdk-js#76]
### Scenario & Reproduction Steps

This likely affect everything that tries to use this SDK, but I encountered it with a SvelteKit app. Simply importing the package triggers this issue.

### Actual Behavior

The following error is printed when the package is imported.

```
Cannot find module '../release/version.js'
Require stack:
- /workspace/node_modules/@1password/sdk/dist/configuration.js
- /workspace/node_modules/@1password/sdk/dist/client_builder.js
- /workspace/node_modules/@1password/sdk/dist/sdk.js
```

This is because the code is trying to reference `version.js`, which is in the repository but not included in the published files. If you explore the npm package files, `version.js` is not in there. I'm guessing the expectation was that the `version.js` would have been rolled up into the released package, but it looks like that didn't work out.

### Expected Behavior

The import should work.

Either the `release/version.js` should be included in the published package, or a bundler like Vite, Rollup, or swc should be used to make sure the `version.js` does in fact get bundled.

### SDK version

0.1.0-beta.14

### Additional information

If you are looking for suggestions, I'd heavily recommend Vite to bundle the library. I use it for a [package of my own](https://github.com/SeriousBug/microfern) if you'd like an example, I was able to use it to bundle for both esm and cjs, and run tests with node and bun (and more if you ever wanted to support edge runtime or browsers)

**Comment by Marton6** [comment]
Thanks for reporting this issue! We will look into fixing it in the next release.

**Comment by AndyTitu** [comment]
@SeriousBug this is solved in the latest version. Use `npm install @1password/sdk@0.1.0-beta.16`.
