### ISSUE TITLE
Resolving secrets doesn't support field metadata attributes

### ISSUE THREAD

**Issue by sgarner** [1Password/onepassword-sdk-js#87]
### Scenario & Reproduction Steps

According to the [Secret Reference Syntax](https://developer.1password.com/docs/cli/secret-reference-syntax#field-and-file-metadata-attributes), parameters can be used to obtain specific attributes of a secret. This is necessary for resolving an OTP field to an OTP code.

In the SDK, this format is not supported. Adding `?attribute=otp` to a secret reference produces an error when calling `client.secrets.resolve()`.

### Actual Behavior

This error occurs:

```
error resolving secret reference: secret reference has invalid format - must be "op://<vault>/<item>/[section/]field"
```

The error goes away when `?attribute=otp` is removed from the end of the secret reference. 

But then the OTP field resolves to another reference URL like `otpauth://totp/<email>?secret=<secret>&issuer=<issuer>`, which is not useful.

### Expected Behavior

Secret references with attributes, like `op://<vault>/<item>/[section/]field?attribute=<attribute>`, should work the same way as they do in the 1Password CLI commands `op read` and `op run`.

### SDK version

0.1.1

**Comment by AndyTitu** [comment]
Hey @sgarner, thanks for opening this issue! We are aware of this limitation/inconsistency. We are working on improving this!

**Comment by MOmarMiraj** [comment]
Hi @sgarner 

With the new release of v0.1.2 of the SDKs, we now support resolving secrets with metadata attributes. Currently, we only support otp/totp. 

I will close this issue as this was specifically for `otp/totp` attributes and if you require support for other attributes, than you can open another issue.
