### ISSUE TITLE
Error resolving secret reference with '.' in the title.

### ISSUE THREAD

**Issue by itzTheMeow** [1Password/onepassword-sdk-js#88]
### Scenario & Reproduction Steps

Getting this error:
```
Error: error resolving secret reference: secret reference has invalid format - must be "op://<vault>/<item>/[section/]field"
```
when fetching secrets with a `.` in the field name
possibly similar to [this](https://github.com/1Password/onepassword-sdk-python/issues/75) from the python SDK

if i change the name of the field to remove the . and change the corresponding url, it fetches properly

this works:
`op://Vault/Item/testname`
this doesn't:
`op://Vault/Item/test.name`

### Actual Behavior

not retreiving values with `.` in field name

### SDK version

0.1.0-beta.11

**Comment by hculea** [comment]
Hey @itzTheMeow - thanks for reaching out. This bug should no longer be present in the latest versions of the SDK. Can you update to v0.1.1 (`npm update @1password/sdk`) and let us know if this is still reproducible?

Thanks!

**Comment by hculea** [comment]
@itzTheMeow I'm going to close this ticket, please do reopen if you still bump into this problem!
