### ISSUE TITLE
Missing Website functionality for item creation

### ISSUE THREAD

**Issue by nikita-tkachov** [1Password/onepassword-sdk-js#90]
### Use Case

I am trying to use the 1pass API to automatically sync passwords from one of my company's internal tools

### Requirements and desired behavior

Allow me to associate a "website" to use for auto-filling. 

### Additional information

I am happy to contribute this feature on my own, if this repo accepts public contributions (or if it's even possible). If not possible, is there also an ETA on this feature being available?

**Comment by hculea** [comment]
Hey @nikita-tkachov,

Thank you for the feature request! I'll forward it our product team for prioritization. 😄 

Additionally, thank you for your offer to help out! I really appreciate it - unfortunately this feature requires changes to code that's not (yet) open source. We've built the SDKs using a common core that's shared across all programming languages in which we build SDKs. This common core shares a lot of logic with our desktop and mobile applications as well as the browser extension. The development of this core is currently too coupled to internal processes and our closed source repository (of the apps) to easily open source. 

While we'd love for this to be available for you and open to contributions, this is not (yet) the case today.
In the meantime, thanks for expressing your interest - gauging the interest for such contributions helps us greatly in prioritizing any initiatives of open-sourcing more of the codebase. 💙

**Comment by sadiaazmal** [comment]
Hi @nikita-tkachov 

I’m Sadia, the product manager leading the SDK initiative, it’s nice to meet you. Thank you submitting your feature request and providing more context. I totally understand the urgency given the volume you are managing. While I can’t provide an exact number of weeks, we plan to start work on this in the upcoming month and I’ll make sure to keep you in the loop as we move forward. Thanks again for your patience and understanding!

**Comment by hculea** [comment]
@nikita-tkachov version 0.1.3 of the JS SDK should now offer the possibility to customize items with autofill websites.

Please let us know if this addresses your use-case - I'll be closing the ticket, but do reopen otherwise!
